# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6016cd0a71e03fa52899027b91ff3f8584a41c41e96261a965ce9ddadd2f13b95200b888a3040b28f69cf3a5c2253e29df5cbba4992b66795e5717017c23917

test:
  secret_key_base: 6d346a986c5d995d2afe0583ca7353ab152adf33dc8d870e670c1cd0606cea113219cdd36d18e8a0c1537cd79cc6e6bd9a1c749b37ff83d21bc7e348e913c6da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
